development:
  secret_key_base: be6f95621504e92355eb79b750234fb1ce9a423916e04a5f888f4641b67f8040a73289edcaa6b3adefaa1078a298e3752ed5388061abaf001926ab9c5855b6dc
  aws_bucket: ''
  aws_access_key_id: ''
  aws_secret_access_key: ''
  username: 'a'
  password: 'b'

test:
  secret_key_base: 6dd19f125028f366563ffd02ced65cb60cd61b0555e8bdf429fd8e1bf8b89d4d233880d55999e2c5f86e9601b4edc1e2e6a5700c2ffa5d61c13644999d202e56
  aws_bucket: ''
  aws_access_key_id: ''
  aws_secret_access_key: ''
  username: 'sian-username'
  password: 'sian-password'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>
